"use strict";
import localization from "./localization.js";
export var Argument;
(function (Argument) {
    var Tre;
    (function (Tre) {
        var Packages;
        (function (Packages) {
            Packages.tre_all_module_have_been_loaded = `◉ ${localization("module_loaded")}`;
            Packages.command_execute_in_progress = `◉ ${localization("module_start_execution")}`;
            Packages.module_available = `◉ ${localization("module_await_for_command")}`;
            Packages.js_shell_error = `${localization("js_shell_error")}`;
            Packages.concat_mode_argument_res = `◉ ${localization("execution_argument")}: ${localization("concat_mode")}`;
            Packages.concat_mode_argument_rton = `◉ ${localization("execution_argument")}: ${localization("encode_rton")}`;
            Packages.concat_atlas_width_argument = `◉ ${localization("execution_argument")}: ${localization("concat_width")}`;
            Packages.concat_atlas_height_argument = `◉ ${localization("execution_argument")}: ${localization("concat_height")}`;
            Packages.decode_width = `◉ ${localization("execution_argument")}: ${localization("decode_width")}`;
            Packages.decode_height = `◉ ${localization("execution_argument")}: ${localization("decode_height")}`;
            Packages.concat_atlas_subgroup_argument = `◉ ${localization("execution_argument")}: ${localization("concat_subgroup")}`;
            Packages.popcap_atlas_member_resize_original_quality = `◉ ${localization("execution_argument")}: ${localization("orig_texture_quality")}`;
            Packages.popcap_atlas_member_resize_modifier_after_quality = `◉ ${localization("execution_argument")}: ${localization("new_texture_quality")}`;
            Packages.method_split_popcap_atlas_texture = `◉ ${localization("execution_argument")}: ${localization("method_split")}`;
            Packages.tre_execution_time_after_process = `◉ ${localization("execution_time")}:`;
            Packages.unknown_reason = `${localization("unknown")}`;
            Packages.error_syntax = `${localization("error")}`;
            Packages.cannot_load_any_modules = `◉ ${localization("execution_failed")}: ${localization("assert_no_module_notify")}`;
            Packages.no_string_has_been_passed = `◉ ${localization("execution_failed")}: ${localization("assert_no_module_loaded_notify")}`;
            Packages.display_cipher_key_readline_argument = `◉ ${localization("execution_argument")}: ${localization("cipher_key")}`;
            Packages.execute_all_files_in_queue = `◉ ${localization("execution_argument")}: ${localization("execute_all_files_in_queue")}`;
            Packages.execute_status_finish = `◉ ${localization("execution_status")}: ${localization("finish")}`;
            Packages.execute_file_size = `◉ ${localization("execution_size")}:`;
            Packages.execute_error_log = `◉ ${localization("execution_error")}:`;
            Packages.execute_error_not_valid_directory_path = `${localization("not_a_directory")}`;
            Packages.execute_error_not_valid_file_path = `${localization("not_a_valid_file_path")}`;
            Packages.execute_reminder_quick_tip = `◉ ${localization("execution_reminder")}: ${localization("pass_me_an_empty_string_to_stop")}`;
            Packages.execute_when_there_is_no_directory_passes_in_tre = `◉ ${localization("execution_warning")}: ${localization("no_args_found")}`;
            Packages.skip_this_argument_to_take_folder_name_as_file_name = `◉ ${localization("execution_reminder")}: ${localization("skip_this_argument_to_take_folder_name_as_file_name")}`;
            Packages.execution_warning_log = `◉ ${localization("execution_warning")}:`;
            Packages.popcap_texture_atlas_cat_max_rects_bin_display_not_atlas_info = `${localization("not_atlas_info")}`;
            Packages.popcap_texture_atlas_cat_max_rects_bin_display_cannot_find_groups_array_in_atlasinfo = `${localization("cannot_find_groups_array")}`;
            Packages.popcap_texture_atlas_cat_max_rects_bin_display_cannot_find_subgroup_in_atlas_info = `${localization("cannot_find_subgroup_key_string")}`;
            Packages.popcap_texture_atlas_cat_max_rects_bin_display_cannot_find_method_in_atlas_info = `${localization("cannot_find_method_key_string")}`;
            Packages.popcap_texture_atlas_cat_max_rects_bin_display_cannot_get_res_data_from_this_atlas_info = `${localization("cannot_get_res_data")}`;
            Packages.popcap_texture_atlas_cat_max_rects_bin_display_not_found_res_indicated_in_subgroups = `${localization("cannot_find_res_data_indicated_in_subgroup")}`;
            Packages.popcap_texture_atlas_cat_max_rects_bin_display_total_sprites_sheet_process_in_this_void = `◉ ${localization("execution_count")}: `;
            Packages.popcap_texture_atlas_cat_max_rects_bin_boolean_question_iz_thiz_pack_smart_pack = `◉ ${localization("execution_argument")}: ${localization("smart_packing_area")}`;
            Packages.popcap_texture_atlas_cat_max_rects_bin_boolean_question_iz_thiz_pack_pot = `◉ ${localization("execution_argument")}: ${localization("pot")}`;
            Packages.popcap_texture_atlas_cat_max_rects_bin_boolean_question_iz_thiz_pack_iz_square = `◉ ${localization("execution_argument")}: ${localization("square_area")}`;
            Packages.popcap_texture_atlas_cat_max_rects_bin_boolean_question_iz_thiz_pack_can_be_allow_for_rotation = `◉ ${localization("execution_argument")}: ${localization("allow_rotation")}`;
            Packages.popcap_texture_atlas_cat_max_rects_bin_boolean_question_padding_size_for_max_rects_bin = `◉ ${localization("execution_argument")}: ${localization("padding_size")}`;
            Packages.popcap_game_zlib_compression_rsgp_unpack_boolean_decode_ptx_for_ptx_rsgp = `◉ ${localization("execution_argument")}: ${localization("decode_ptx")}`;
            Packages.popcap_game_rewrite_mode = `◉ ${localization("execution_argument")}: ${localization("rewrite_mode")}`;
            Packages.popcap_res_to_atlasinfo_notify_atlas_info_method = `◉ ${localization("execution_argument")}: ${localization("atlasinfo_method_split")}`;
            Packages.tre_void_json_patch_ask_drag_file = `◉ ${localization("execution_argument")}: ${localization("json_patch_drag_json_apply_patch")}`;
            Packages.tre_void_json_patch_finish_apply_patch = `◉ ${localization("execution_finish")}: ${localization("json_patch_applied_patch")}`;
            Packages.tre_void_json_patch_generator_execution_received = `◉ ${localization("execution_received")}: ${localization("old_json")}`;
            Packages.tre_void_json_patch_generator_new_execution_generator = `◉ ${localization("execution_argument")}: ${localization("new_json")}`;
            Packages.tre_void_json_patch_finish_write_patch = `◉ ${localization("execution_finish")}: ${localization("generated_patch")}`;
            Packages.tre_void_upscaler_real_esrgan_upscale_model = `◉ ${localization("execution_argument")}: ${localization("upscale_model")}`;
            Packages.tre_void_upscaler_real_esrgan_upscale_ratio = `◉ ${localization("execution_argument")}: ${localization("upscale_ratio")}`;
            Packages.res_cat_concat_mode_safe = `      1. ${localization("res_cat_concat_mode_safe")}`;
            Packages.res_cat_concat_mode_safe_fix = `      2. ${localization("res_cat_concat_mode_safe_fix")}`;
            Packages.res_cat_concat_no_encode_rton = `      0. ${localization("res_cat_concat_no_encode_rton")}`;
            Packages.res_cat_concat_encode_rton = `      1. ${localization("res_cat_concat_encode_rton")}`;
            Packages.default_boolean_with_false = `      0. ${localization("default_boolean_with_false")}`;
            Packages.default_boolean_with_true = `      1. ${localization("default_boolean_with_true")}`;
            Packages.method_split_popcap_atlas_texture_with_path_extension = `      1. ${localization("method_split_popcap_atlas_texture_with_path_extension")}`;
            Packages.method_split_popcap_atlas_texture_with_id_extension = `      2. ${localization("method_split_popcap_atlas_texture_with_id_extension")}`;
            Packages.method_resources_local_compare_drag_input = `◉ ${localization("execution_argument")}: ${localization("local_compare_bundle_input_argument")}`;
            Packages.local_compare_received = `◉ ${localization("execution_received")}: ${localization("popcap_resources_local_compare_vanilla_res")}`;
            Packages.popcap_lawnstring_old_obtained = `◉ ${localization("execution_received")}: ${localization("popcap_lawnstrings_old_obtained")}`;
            Packages.popcap_lawnstrings_new_require = `◉ ${localization("execution_argument")}: ${localization("popcap_lawnstrings_new_require")}`;
            Packages.res_rewrite_mode_safe = `      1. ${localization("res_rewrite_mode_safe")}`;
            Packages.res_rewrite_mode_safe_fix = `      2. ${localization("res_rewrite_mode_safe_fix")}`;
            Packages.old_popcap_support = `      1. ${localization("old_popcap_support")}`;
            Packages.new_popcap_support = `      2. ${localization("new_popcap_support")}`;
            Packages.popcap_resource_support_argument = `◉ ${localization("execution_argument")}: ${localization("popcap_resource_support_argument")}`;
            Packages.popcap_support_trim = `◉ ${localization("execution_argument")}: ${localization("is_trimming_mode")}`;
        })(Packages = Tre.Packages || (Tre.Packages = {}));
    })(Tre = Argument.Tre || (Argument.Tre = {}));
})(Argument || (Argument = {}));
